name = "clap-site-dev"
type = "webpack"
account_id = "efb289061241436254219b424fcea4cf"
workers_dev = true
route = ""
zone_id = ""

[site]
  bucket = "./build"
  entry-point = "workers-site"

[vars]
  JEKYLL_ENV = 'development'

[env.staging]
  name = "clap-site-stage"
  route = "https://getclaps.dev/*"
  zone_id = "a0f647422a7f0fba9b734898e8a7883f"

  [env.staging.vars]
    JEKYLL_ENV = 'staging'

[env.production]
  name = "clap-site-production"
  route = "https://clap-button.com/*"
  zone_id = "921f99936380db6078d69bc9bdf50bc7"

  [env.production.vars]
    JEKYLL_ENV = 'production'