name: Deploy

on:
  push:
    tags: 
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@v2
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.GH_REPO_PAT }}
        with:
          token: ${{ secrets.GH_REPO_PAT }}
          jekyll_env: production
          build_only: true
          prebuild_commands: sed -i 's/getclaps.dev/getclaps.app/' _config.yaml
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: production